SELECT
    *,
    ABS(DAYS_BIRTH) / 365.0 AS AGE_YEARS,
    CASE
        WHEN DAYS_EMPLOYED = 365243 THEN NULL
        ELSE ABS(DAYS_EMPLOYED) / 365.0
    END AS EMPLOYED_YEARS,
    CASE
        WHEN DAYS_EMPLOYED = 365243 THEN 1
        ELSE 0
    END AS DAYS_EMPLOYED_ANOMALY,
    AMT_INCOME_TOTAL / NULLIF(AMT_CREDIT, 0) AS INCOME_CREDIT_RATIO,
    AMT_ANNUITY / NULLIF(AMT_INCOME_TOTAL, 0) AS ANNUITY_INCOME_RATIO,
    AMT_CREDIT / NULLIF(AMT_GOODS_PRICE, 0) AS CREDIT_GOODS_RATIO
FROM bronze_application