WITH bureau_balance_agg AS (
    SELECT
        SK_ID_BUREAU,
        COUNT(*) AS BUREAU_BALANCE_MONTHS_COUNT,
        AVG(CASE WHEN STATUS IN ('1','2','3','4','5') THEN 1 ELSE 0 END) AS BUREAU_BAD_STATUS_RATE
    FROM bronze_bureau_balance
    GROUP BY SK_ID_BUREAU
),
bureau_with_balance AS (
    SELECT
        b.*,
        bb.BUREAU_BAD_STATUS_RATE
    FROM bronze_bureau b
    LEFT JOIN bureau_balance_agg bb ON b.SK_ID_BUREAU = bb.SK_ID_BUREAU
)
SELECT
    SK_ID_CURR,
    COUNT(DISTINCT SK_ID_BUREAU) AS BUREAU_LOAN_COUNT,
    SUM(CASE WHEN CREDIT_ACTIVE = 'Active' THEN 1 ELSE 0 END) AS BUREAU_ACTIVE_COUNT,
    SUM(CASE WHEN CREDIT_ACTIVE = 'Closed' THEN 1 ELSE 0 END) AS BUREAU_CLOSED_COUNT,
    MAX(AMT_CREDIT_MAX_OVERDUE) AS BUREAU_MAX_OVERDUE,
    SUM(AMT_CREDIT_SUM_DEBT) AS BUREAU_TOTAL_DEBT,
    SUM(AMT_CREDIT_SUM) AS BUREAU_TOTAL_CREDIT,
    AVG(DAYS_CREDIT_OVERDUE) AS BUREAU_AVG_DPD,
    AVG(BUREAU_BAD_STATUS_RATE) AS BUREAU_AVG_BAD_STATUS_RATE
FROM bureau_with_balance
GROUP BY SK_ID_CURR