paths:
  raw_data_dir: "sql/dev/source_data"
  output_bronze_dir: "data/bronze"
  output_staging_dir: "data/staging"
  output_mart_dir: "data/mart"
  ge_root_dir: "great_expectations"
  log_dir: "log"

sources:
  - name: "application"
    file: "HC_application_train.csv"
  - name: "bureau"
    file: "HC_bureau.csv"
  - name: "bureau_balance"
    file: "HC_bureau_balance.csv"
  - name: "previous_application"
    file: "HC_previous_application.csv"
  - name: "installments_payments"
    file: "HC_installments_payments.csv"
  - name: "pos_cash_balance"
    file: "HC_POS_CASH_balance.csv"
  - name: "credit_card_balance"
    file: "HC_credit_card_balance.csv"

prefect:
  schedule: "0 1 * * *"
  task_retries: 2
  task_retry_delay_seconds: 30

ge:
  bronze_checkpoint: "bronze_checkpoint.yaml"
  staging_checkpoint: "staging_checkpoint.yaml"
  mart_checkpoint: "mart_checkpoint.yaml"