-- mart.risk_model_features
CREATE TABLE IF NOT EXISTS mart.risk_model_features (
    sk_id_curr              INTEGER PRIMARY KEY,
    target                  SMALLINT,
    amt_income_total        NUMERIC(18,2),
    amt_credit              NUMERIC(18,2),
    amt_annuity             NUMERIC(18,2),
    amt_goods_price         NUMERIC(18,2),
    ext_source_1            NUMERIC(18,8),
    ext_source_2            NUMERIC(18,8),
    ext_source_3            NUMERIC(18,8),
    age_years               NUMERIC(6,2),
    employed_years          NUMERIC(6,2),
    days_employed_anomaly   SMALLINT,
    income_credit_ratio     NUMERIC(12,6),
    annuity_income_ratio    NUMERIC(12,6),
    credit_goods_ratio      NUMERIC(12,6),
    name_contract_type      VARCHAR(50),
    code_gender             VARCHAR(5),
    name_income_type        VARCHAR(100),
    name_education_type     VARCHAR(100),
    name_family_status      VARCHAR(100),
    name_housing_type       VARCHAR(100),
    region_rating_client    SMALLINT,
    bureau_loan_count       INTEGER,
    bureau_active_count     INTEGER,
    bureau_closed_count     INTEGER,
    bureau_max_overdue      NUMERIC(18,2),
    bureau_total_debt       NUMERIC(18,2),
    bureau_total_credit     NUMERIC(18,2),
    bureau_avg_dpd          NUMERIC(10,4),
    bureau_bad_status_rate  NUMERIC(8,6),
    prev_app_count          INTEGER,
    prev_approved_count     INTEGER,
    prev_refused_count      INTEGER,
    prev_approval_rate      NUMERIC(8,6),
    prev_avg_credit         NUMERIC(18,2),
    prev_max_credit         NUMERIC(18,2),
    instalment_count        INTEGER,
    instalment_late_count   INTEGER,
    instalment_late_rate    NUMERIC(8,6),
    instalment_avg_delay    NUMERIC(10,4),
    instalment_amt_shortfall NUMERIC(18,2),
    pos_months_count        INTEGER,
    pos_max_dpd             INTEGER,
    pos_avg_dpd             NUMERIC(10,4),
    pos_overdue_months      INTEGER,
    pos_overdue_rate        NUMERIC(8,6),
    cc_months_count         INTEGER,
    cc_avg_balance          NUMERIC(18,2),
    cc_max_balance          NUMERIC(18,2),
    cc_avg_utilization      NUMERIC(8,6),
    cc_avg_payment_ratio    NUMERIC(8,6),
    cc_max_dpd              INTEGER,
    _loaded_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- mart.risk_report_summary
CREATE TABLE IF NOT EXISTS mart.risk_report_summary (
    sk_id_curr              INTEGER PRIMARY KEY,
    target                  SMALLINT,
    age_years               NUMERIC(6,2),
    name_income_type        VARCHAR(100),
    amt_income_total        NUMERIC(18,2),
    amt_credit              NUMERIC(18,2),
    income_credit_ratio     NUMERIC(12,6),
    ext_source_2            NUMERIC(18,8),
    bureau_max_overdue      NUMERIC(18,2),
    risk_tier               VARCHAR(10),
    _loaded_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- mart.default_cohort
CREATE TABLE IF NOT EXISTS mart.default_cohort (
    cohort_dim      VARCHAR(100),
    cohort_value    VARCHAR(200),
    total_count     INTEGER,
    default_count   INTEGER,
    default_rate    NUMERIC(8,6),
    _loaded_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (cohort_dim, cohort_value)
);