-- Default rate theo từng cohort dimension
-- Pattern: UNION ALL nhiều GROUP BY, mỗi GROUP BY = 1 dimension
SELECT 'NAME_INCOME_TYPE'   AS COHORT_DIM, NAME_INCOME_TYPE   AS COHORT_VALUE, COUNT(*) AS TOTAL_COUNT, SUM(TARGET) AS DEFAULT_COUNT, AVG(TARGET) AS DEFAULT_RATE FROM stg_application GROUP BY NAME_INCOME_TYPE
UNION ALL
SELECT 'NAME_EDUCATION_TYPE' AS COHORT_DIM, NAME_EDUCATION_TYPE AS COHORT_VALUE, COUNT(*) AS TOTAL_COUNT, SUM(TARGET) AS DEFAULT_COUNT, AVG(TARGET) AS DEFAULT_RATE FROM stg_application GROUP BY NAME_EDUCATION_TYPE
UNION ALL
SELECT 'NAME_FAMILY_STATUS'  AS COHORT_DIM, NAME_FAMILY_STATUS  AS COHORT_VALUE, COUNT(*) AS TOTAL_COUNT, SUM(TARGET) AS DEFAULT_COUNT, AVG(TARGET) AS DEFAULT_RATE FROM stg_application GROUP BY NAME_FAMILY_STATUS
UNION ALL
SELECT 'NAME_HOUSING_TYPE'   AS COHORT_DIM, CAST(NAME_HOUSING_TYPE AS VARCHAR(200))   AS COHORT_VALUE, COUNT(*) AS TOTAL_COUNT, SUM(TARGET) AS DEFAULT_COUNT, AVG(TARGET) AS DEFAULT_RATE FROM stg_application GROUP BY NAME_HOUSING_TYPE
UNION ALL
SELECT 'REGION_RATING_CLIENT' AS COHORT_DIM, CAST(REGION_RATING_CLIENT AS VARCHAR(200)) AS COHORT_VALUE, COUNT(*) AS TOTAL_COUNT, SUM(TARGET) AS DEFAULT_COUNT, AVG(TARGET) AS DEFAULT_RATE FROM stg_application GROUP BY REGION_RATING_CLIENT
UNION ALL
SELECT 'NAME_CONTRACT_TYPE'  AS COHORT_DIM, NAME_CONTRACT_TYPE  AS COHORT_VALUE, COUNT(*) AS TOTAL_COUNT, SUM(TARGET) AS DEFAULT_COUNT, AVG(TARGET) AS DEFAULT_RATE FROM stg_application GROUP BY NAME_CONTRACT_TYPE
